In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from scipy import stats

In [16]:
# 1. How likely is it that you roll doubles when rolling two dice?

outcomes = list(range(1,7))
outcomes

n_trials = 100_000

dice_rolls = (np.random.choice(outcomes, n_trials * 2)).reshape(100_000, 2)

In [17]:
dice_rolls

array([[4, 6],
       [2, 1],
       [2, 4],
       ...,
       [1, 4],
       [5, 1],
       [4, 2]])

In [51]:
dr = [elem[0]==elem[1] for elem in dice_rolls] #create list to get Boolean values of doubles occurring

In [57]:
sum(dr)/len(dr)

0.16648

# Bonus Questions

In [14]:
# 2. If you flip 8 coins, what is the probability of getting exactly 3 heads? 
# What is the probability of getting more than 3 heads?

H = 1
T = 0

head_tails = np.random.choice([H,T], [1_000_000, 8])

In [15]:
(head_tails.sum(axis=1) == 3).mean() #first part to get Boolean values where exactly three coins were heads. mean()
                                    # is to get the probability that it occurs

0.218562

In [3]:
stats.binom(8, .5).pmf(3) #using stats module

0.21874999999999992

In [69]:
# For more than 3 heads, just change operand

(head_tails.sum(axis=1) > 3).mean()

0.63594

In [4]:
stats.binom(8, .5).sf(3) #using scipy.stats

0.63671875

In [8]:
# 3. There are approximitely 3 web development cohorts for every 1 data science cohort at Codeup. 
# Assuming that Codeup randomly selects an alumni to put on a billboard, what are the odds that the two billboards 
# I drive past both have data science students on them?

WD = 0
DS = 1

billboard = np.random.choice([WD, WD, WD, DS], [1_000_000, 2])

In [9]:
(billboard.sum(axis=1) == 2).mean()

0.062608

In [5]:
stats.binom(2, .25).pmf(2) #using stats module

0.0625

In [86]:
# 4. Codeup students buy, on average, 3 poptart packages with a standard deviation of 1.5 a day from the snack 
# vending machine. If on monday the machine is restocked with 17 poptart packages, how likely is it that I will be 
# able to buy some poptarts on Friday afternoon? 

# (Remember, if you have mean and standard deviation, use the np.random.normal) You'll need to make a judgement call 
# on how to handle some of your values

daily_pt = np.random.normal(3, 1.5, [100_000,5]) #getting samples of how many poptarts are eaten a day for five days

In [90]:
have_pt = 17 - daily_pt.sum(axis=1) # gets array of how many poptarts are remaining at end of Friday afternoon

In [91]:
(have_pt >= 1).mean() # gets the probability of whether you can buy at least one poptart by then

0.61688

In [92]:
# 5. Compare Heights

# Men have an average height of 178 cm and standard deviation of 8cm.
# Women have a mean of 170, sd = 6cm.
# Since you have means and standard deviations, you can use np.random.normal to generate observations.
# If a man and woman are chosen at random, what is the likelihood the woman is taller than the man?

men = np.random.normal(178, 8, 100_000)
women = np.random.normal(170, 6, 100_000)

women > men

array([False, False, False, ..., False,  True, False])

In [93]:
(women > men).mean()

0.21332

In [23]:
# When installing anaconda on a student's computer, there's a 1 in 250 chance that the download is corrupted and the 
# installation fails. What are the odds that after having 50 students download anaconda, no one has an installation 
# issue? 100 students?

corrupt = [0 for n in range(250)]
corrupt[0] = 1
corrupt

[1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0]

In [24]:
downloads = np.random.choice(corrupt, [1_000_000, 50])
downloads

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]])

In [26]:
(downloads.sum(axis=1) == 0).mean() # This is for 50 students

0.81802

In [28]:
downloads = np.random.choice(corrupt, [1_000_000, 100]) #For 100 students
(downloads.sum(axis=1) == 0).mean()

0.669081

In [29]:
# What is the probability that we observe an installation issue within the first 150 students that download anaconda?

downloads = np.random.choice(corrupt, [1_000_000, 150])
(downloads.sum(axis=1) >= 1).mean()

0.451899

In [30]:
# How likely is it that 450 students all download anaconda without an issue?

downloads = np.random.choice(corrupt, [1_000_000, 450]) #For 450 students
(downloads.sum(axis=1) == 0).mean()

0.164405

In [ ]:
# 7. There's a 70% chance on any given day that there will be at least one food truck at Travis Park. 
# However, you haven't seen a food truck there in 3 days. How unlikely is this?

# How likely is it that a food truck will show up sometime this week?



In [40]:
# 8. If 23 people are in the same room, what are the odds that two of them share a birthday? 
# What if it's 20 people? 40?

birthday = np.random.choice(range(1,365), (100_000, 23))

birthday = pd.DataFrame(birthday)

In [42]:
(birthday.nunique(axis=1) < 23).mean()

0.50848